# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x61i.proto\x12\naura.ai.v1\"b\n\x12UploadModelRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x12\n\nsource_key\x18\x03 \x01(\t\x12\x15\n\rsource_sha256\x18\x04 \x01(\t\"\x1d\n\x0fGetModelRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x13\n\x11ListModelsRequest\" \n\x12\x44\x65leteModelRequest\x12\n\n\x02id\x18\x01 \x01(\t\"&\n\x13\x44\x65leteModelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x9d\x01\n\x1aUpdateModelCompiledRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0c\x63ompiled_key\x18\x02 \x01(\t\x12\x17\n\x0f\x63ompiled_sha256\x18\x03 \x01(\t\x12\x15\n\rhardware_type\x18\x04 \x01(\t\x12\x16\n\x0e\x63ompile_status\x18\x05 \x01(\t\x12\x15\n\rcompile_error\x18\x06 \x01(\t\"\xf2\x01\n\rModelResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x12\n\nsource_key\x18\x04 \x01(\t\x12\x15\n\rsource_sha256\x18\x05 \x01(\t\x12\x14\n\x0c\x63ompiled_key\x18\x06 \x01(\t\x12\x17\n\x0f\x63ompiled_sha256\x18\x07 \x01(\t\x12\x15\n\rhardware_type\x18\x08 \x01(\t\x12\x16\n\x0e\x63ompile_status\x18\t \x01(\t\x12\x15\n\rcompile_error\x18\n \x01(\t\x12\x12\n\ncreated_at\x18\x0b \x01(\t\"?\n\x12ListModelsResponse\x12)\n\x06models\x18\x01 \x03(\x0b\x32\x19.aura.ai.v1.ModelResponse2\x90\x03\n\tAIService\x12H\n\x0bUploadModel\x12\x1e.aura.ai.v1.UploadModelRequest\x1a\x19.aura.ai.v1.ModelResponse\x12\x42\n\x08GetModel\x12\x1b.aura.ai.v1.GetModelRequest\x1a\x19.aura.ai.v1.ModelResponse\x12K\n\nListModels\x12\x1d.aura.ai.v1.ListModelsRequest\x1a\x1e.aura.ai.v1.ListModelsResponse\x12N\n\x0b\x44\x65leteModel\x12\x1e.aura.ai.v1.DeleteModelRequest\x1a\x1f.aura.ai.v1.DeleteModelResponse\x12X\n\x13UpdateModelCompiled\x12&.aura.ai.v1.UpdateModelCompiledRequest\x1a\x19.aura.ai.v1.ModelResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADMODELREQUEST']._serialized_start=24
  _globals['_UPLOADMODELREQUEST']._serialized_end=122
  _globals['_GETMODELREQUEST']._serialized_start=124
  _globals['_GETMODELREQUEST']._serialized_end=153
  _globals['_LISTMODELSREQUEST']._serialized_start=155
  _globals['_LISTMODELSREQUEST']._serialized_end=174
  _globals['_DELETEMODELREQUEST']._serialized_start=176
  _globals['_DELETEMODELREQUEST']._serialized_end=208
  _globals['_DELETEMODELRESPONSE']._serialized_start=210
  _globals['_DELETEMODELRESPONSE']._serialized_end=248
  _globals['_UPDATEMODELCOMPILEDREQUEST']._serialized_start=251
  _globals['_UPDATEMODELCOMPILEDREQUEST']._serialized_end=408
  _globals['_MODELRESPONSE']._serialized_start=411
  _globals['_MODELRESPONSE']._serialized_end=653
  _globals['_LISTMODELSRESPONSE']._serialized_start=655
  _globals['_LISTMODELSRESPONSE']._serialized_end=718
  _globals['_AISERVICE']._serialized_start=721
  _globals['_AISERVICE']._serialized_end=1121
# @@protoc_insertion_point(module_scope)
