# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: compilation.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'compilation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63ompilation.proto\x12\x13\x61ura.compilation.v1\"\xad\x01\n\x13\x43ompileModelRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x12\n\nsource_key\x18\x02 \x01(\t\x12\x15\n\rhardware_type\x18\x03 \x01(\t\x12\x13\n\x0bnum_classes\x18\x04 \x01(\x05\x12\x13\n\x0b\x63lass_names\x18\x05 \x03(\t\x12\x1a\n\x12\x64\x61taset_version_id\x18\x06 \x01(\t\x12\x13\n\x0b\x64\x61taset_key\x18\x07 \x01(\t\"/\n\x1bGetCompilationStatusRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\"v\n\x14\x43ompileModelResponse\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x14\n\x0c\x63ompiled_key\x18\x03 \x01(\t\x12\x17\n\x0f\x63ompiled_sha256\x18\x04 \x01(\t\x12\r\n\x05\x65rror\x18\x05 \x01(\t2\xee\x01\n\x12\x43ompilationService\x12\x63\n\x0c\x43ompileModel\x12(.aura.compilation.v1.CompileModelRequest\x1a).aura.compilation.v1.CompileModelResponse\x12s\n\x14GetCompilationStatus\x12\x30.aura.compilation.v1.GetCompilationStatusRequest\x1a).aura.compilation.v1.CompileModelResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'compilation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPILEMODELREQUEST']._serialized_start=43
  _globals['_COMPILEMODELREQUEST']._serialized_end=216
  _globals['_GETCOMPILATIONSTATUSREQUEST']._serialized_start=218
  _globals['_GETCOMPILATIONSTATUSREQUEST']._serialized_end=265
  _globals['_COMPILEMODELRESPONSE']._serialized_start=267
  _globals['_COMPILEMODELRESPONSE']._serialized_end=385
  _globals['_COMPILATIONSERVICE']._serialized_start=388
  _globals['_COMPILATIONSERVICE']._serialized_end=626
# @@protoc_insertion_point(module_scope)
