# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'device.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65vice.proto\x12\x0e\x61ura.device.v1\"O\n\x13\x43reateDeviceRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rhardware_type\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"\x1e\n\x10GetDeviceRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x14\n\x12ListDevicesRequest\"!\n\x13\x44\x65leteDeviceRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\'\n\x14\x44\x65leteDeviceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"7\n\x19UpdateDeviceStatusRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"\x90\x01\n\x0e\x44\x65viceResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x15\n\rhardware_type\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x14\n\x0clast_seen_at\x18\x06 \x01(\t\x12\x12\n\ncreated_at\x18\x07 \x01(\t\"F\n\x13ListDevicesResponse\x12/\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x1e.aura.device.v1.DeviceResponse2\xc7\x03\n\rDeviceService\x12S\n\x0c\x43reateDevice\x12#.aura.device.v1.CreateDeviceRequest\x1a\x1e.aura.device.v1.DeviceResponse\x12M\n\tGetDevice\x12 .aura.device.v1.GetDeviceRequest\x1a\x1e.aura.device.v1.DeviceResponse\x12V\n\x0bListDevices\x12\".aura.device.v1.ListDevicesRequest\x1a#.aura.device.v1.ListDevicesResponse\x12Y\n\x0c\x44\x65leteDevice\x12#.aura.device.v1.DeleteDeviceRequest\x1a$.aura.device.v1.DeleteDeviceResponse\x12_\n\x12UpdateDeviceStatus\x12).aura.device.v1.UpdateDeviceStatusRequest\x1a\x1e.aura.device.v1.DeviceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEDEVICEREQUEST']._serialized_start=32
  _globals['_CREATEDEVICEREQUEST']._serialized_end=111
  _globals['_GETDEVICEREQUEST']._serialized_start=113
  _globals['_GETDEVICEREQUEST']._serialized_end=143
  _globals['_LISTDEVICESREQUEST']._serialized_start=145
  _globals['_LISTDEVICESREQUEST']._serialized_end=165
  _globals['_DELETEDEVICEREQUEST']._serialized_start=167
  _globals['_DELETEDEVICEREQUEST']._serialized_end=200
  _globals['_DELETEDEVICERESPONSE']._serialized_start=202
  _globals['_DELETEDEVICERESPONSE']._serialized_end=241
  _globals['_UPDATEDEVICESTATUSREQUEST']._serialized_start=243
  _globals['_UPDATEDEVICESTATUSREQUEST']._serialized_end=298
  _globals['_DEVICERESPONSE']._serialized_start=301
  _globals['_DEVICERESPONSE']._serialized_end=445
  _globals['_LISTDEVICESRESPONSE']._serialized_start=447
  _globals['_LISTDEVICESRESPONSE']._serialized_end=517
  _globals['_DEVICESERVICE']._serialized_start=520
  _globals['_DEVICESERVICE']._serialized_end=975
# @@protoc_insertion_point(module_scope)
