# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: monitoring.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'monitoring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10monitoring.proto\x12\x12\x61ura.monitoring.v1\"*\n\x15GetDeviceStateRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\"\x19\n\x17ListDeviceStatesRequest\">\n\x1aGetInferenceResultsRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"\xde\x01\n\x13\x44\x65viceStateResponse\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x17\n\x0f\x61\x63tive_model_id\x18\x03 \x01(\t\x12\x18\n\x10\x61\x63tive_script_id\x18\x04 \x01(\t\x12\x1c\n\x14\x61\x63tive_deployment_id\x18\x05 \x01(\t\x12\x13\n\x0b\x63pu_percent\x18\x06 \x01(\x02\x12\x13\n\x0bram_percent\x18\x07 \x01(\x02\x12\x13\n\x0bram_used_mb\x18\x08 \x01(\x02\x12\x14\n\x0clast_seen_at\x18\t \x01(\t\"S\n\x18ListDeviceStatesResponse\x12\x37\n\x06states\x18\x01 \x03(\x0b\x32\'.aura.monitoring.v1.DeviceStateResponse\"c\n\x0fInferenceResult\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x15\n\rdeployment_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x13\n\x0bresult_json\x18\x04 \x01(\t\"S\n\x1bGetInferenceResultsResponse\x12\x34\n\x07results\x18\x01 \x03(\x0b\x32#.aura.monitoring.v1.InferenceResult2\xe0\x02\n\x11MonitoringService\x12\x64\n\x0eGetDeviceState\x12).aura.monitoring.v1.GetDeviceStateRequest\x1a\'.aura.monitoring.v1.DeviceStateResponse\x12m\n\x10ListDeviceStates\x12+.aura.monitoring.v1.ListDeviceStatesRequest\x1a,.aura.monitoring.v1.ListDeviceStatesResponse\x12v\n\x13GetInferenceResults\x12..aura.monitoring.v1.GetInferenceResultsRequest\x1a/.aura.monitoring.v1.GetInferenceResultsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'monitoring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETDEVICESTATEREQUEST']._serialized_start=40
  _globals['_GETDEVICESTATEREQUEST']._serialized_end=82
  _globals['_LISTDEVICESTATESREQUEST']._serialized_start=84
  _globals['_LISTDEVICESTATESREQUEST']._serialized_end=109
  _globals['_GETINFERENCERESULTSREQUEST']._serialized_start=111
  _globals['_GETINFERENCERESULTSREQUEST']._serialized_end=173
  _globals['_DEVICESTATERESPONSE']._serialized_start=176
  _globals['_DEVICESTATERESPONSE']._serialized_end=398
  _globals['_LISTDEVICESTATESRESPONSE']._serialized_start=400
  _globals['_LISTDEVICESTATESRESPONSE']._serialized_end=483
  _globals['_INFERENCERESULT']._serialized_start=485
  _globals['_INFERENCERESULT']._serialized_end=584
  _globals['_GETINFERENCERESULTSRESPONSE']._serialized_start=586
  _globals['_GETINFERENCERESULTSRESPONSE']._serialized_end=669
  _globals['_MONITORINGSERVICE']._serialized_start=672
  _globals['_MONITORINGSERVICE']._serialized_end=1024
# @@protoc_insertion_point(module_scope)
