# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: script.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'script.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cscript.proto\x12\x0e\x61ura.script.v1\"z\n\x13UploadScriptRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x15\n\rhardware_type\x18\x03 \x01(\t\x12\x12\n\nscript_key\x18\x04 \x01(\t\x12\x15\n\rscript_sha256\x18\x05 \x01(\t\"\x1e\n\x10GetScriptRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x14\n\x12ListScriptsRequest\"!\n\x13\x44\x65leteScriptRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\'\n\x14\x44\x65leteScriptResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x95\x01\n\x0eScriptResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x15\n\rhardware_type\x18\x04 \x01(\t\x12\x12\n\nscript_key\x18\x05 \x01(\t\x12\x15\n\rscript_sha256\x18\x06 \x01(\t\x12\x12\n\ncreated_at\x18\x07 \x01(\t\"F\n\x13ListScriptsResponse\x12/\n\x07scripts\x18\x01 \x03(\x0b\x32\x1e.aura.script.v1.ScriptResponse2\xe6\x02\n\rScriptService\x12S\n\x0cUploadScript\x12#.aura.script.v1.UploadScriptRequest\x1a\x1e.aura.script.v1.ScriptResponse\x12M\n\tGetScript\x12 .aura.script.v1.GetScriptRequest\x1a\x1e.aura.script.v1.ScriptResponse\x12V\n\x0bListScripts\x12\".aura.script.v1.ListScriptsRequest\x1a#.aura.script.v1.ListScriptsResponse\x12Y\n\x0c\x44\x65leteScript\x12#.aura.script.v1.DeleteScriptRequest\x1a$.aura.script.v1.DeleteScriptResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'script_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADSCRIPTREQUEST']._serialized_start=32
  _globals['_UPLOADSCRIPTREQUEST']._serialized_end=154
  _globals['_GETSCRIPTREQUEST']._serialized_start=156
  _globals['_GETSCRIPTREQUEST']._serialized_end=186
  _globals['_LISTSCRIPTSREQUEST']._serialized_start=188
  _globals['_LISTSCRIPTSREQUEST']._serialized_end=208
  _globals['_DELETESCRIPTREQUEST']._serialized_start=210
  _globals['_DELETESCRIPTREQUEST']._serialized_end=243
  _globals['_DELETESCRIPTRESPONSE']._serialized_start=245
  _globals['_DELETESCRIPTRESPONSE']._serialized_end=284
  _globals['_SCRIPTRESPONSE']._serialized_start=287
  _globals['_SCRIPTRESPONSE']._serialized_end=436
  _globals['_LISTSCRIPTSRESPONSE']._serialized_start=438
  _globals['_LISTSCRIPTSRESPONSE']._serialized_end=508
  _globals['_SCRIPTSERVICE']._serialized_start=511
  _globals['_SCRIPTSERVICE']._serialized_end=869
# @@protoc_insertion_point(module_scope)
